# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at http://mozilla.org/MPL/2.0/.


### Unified Toolbar Item Label strings

spacer-label = 伸縮自在のスペース
search-bar-label = 検索
toolbar-write-message-label = 作成
toolbar-write-message =
    .title = @@New-CMD@@メッセージを作成します
toolbar-move-to-label = 移動先
toolbar-move-to =
    .title = 選択したメッセージを移動します
toolbar-unifinder-label = 予定を検索
toolbar-unifinder =
    .title = 予定検索ペインを開閉します
toolbar-folder-location-label = フォルダーバー
toolbar-folder-location =
    .title = フォルダーを切り替えます
toolbar-edit-event-label = 編集
toolbar-edit-event =
    .title = 選択した予定または ToDo を編集します
toolbar-get-messages-label = 受信
toolbar-get-messages =
    .title = すべてのアカウントの新着メッセージを受信します
toolbar-reply-label = 返信
toolbar-reply =
    .title = メッセージに返信します
toolbar-reply-all-label = 全員に返信
toolbar-reply-all =
    .title = 送受信者全員に返信します
toolbar-reply-to-list-label = リストに返信
toolbar-reply-to-list =
    .title = メーリングリストに返信します
toolbar-redirect-label = リダイレクト
toolbar-redirect =
    .title = 選択したメッセージをリダイレクトします
toolbar-archive-label = アーカイブ
toolbar-archive =
    .title = 選択したメッセージをアーカイブに移動します
toolbar-conversation-label = スレッド
toolbar-conversation =
    .title = 選択したメッセージのスレッドを表示します
toolbar-previous-unread-label = 前の未読へ
toolbar-previous-unread =
    .title = 前の未読メッセージに移動します
toolbar-previous-label = 前へ
toolbar-previous =
    .title = 前のメッセージに移動します
toolbar-next-unread-label = 次の未読へ
toolbar-next-unread =
    .title = 次の未読メッセージに移動します
toolbar-next-label = 次へ
toolbar-next =
    .title = 次のメッセージに移動します
toolbar-junk-label = 迷惑メール
toolbar-junk =
    .title = 選択したメッセージに迷惑マークを付けます
toolbar-delete-label = 削除
toolbar-delete =
    .title = 選択したメッセージまたはフォルダーを削除します
toolbar-compact-label = 最適化
toolbar-compact =
    .title = 削除したメッセージをフォルダーから消去します
toolbar-add-as-event-label = 予定に追加
toolbar-add-as-event =
    .title = メッセージからカレンダー情報を抽出し、カレンダーの予定に追加します
toolbar-add-as-task-label = ToDo に追加
toolbar-add-as-task =
    .title = メッセージからカレンダー情報を抽出し、カレンダーの ToDo に追加します
toolbar-tag-message-label = タグ
toolbar-tag-message =
    .title = メッセージにタグを付けます
toolbar-forward-inline-label = 転送
toolbar-forward-inline =
    .title = 選択したメッセージをメッセージ本文として転送します
toolbar-forward-attachment-label = 添付ファイルとして転送
toolbar-forward-attachment =
    .title = 選択したメッセージを添付ファイルとして転送します
toolbar-mark-as-label = マーク
toolbar-mark-as =
    .title = メッセージにマークを付けます
toolbar-view-picker-label = ビュー
toolbar-view-picker =
    .title = 現在のフォルダーのビューをカスタマイズします
toolbar-address-book-label = アドレス帳
toolbar-address-book =
    .title = アドレス帳を開きます
toolbar-chat-label = チャット
toolbar-chat =
    .title = チャットタブを開きます
toolbar-add-ons-and-themes-label = アドオンとテーマ
toolbar-add-ons-and-themes =
    .title = アドオンを管理します
toolbar-calendar-label = カレンダー
toolbar-calendar =
    .title = カレンダータブに切り替えます
toolbar-tasks-label = ToDo
toolbar-tasks =
    .title = ToDo タブに切り替えます
toolbar-mail-label = メール
toolbar-mail =
    .title = メールタブに切り替えます
toolbar-print-label = @@Print@@
toolbar-print =
    .title = メッセージを@@Print@@します
toolbar-quick-filter-bar-label = クイックフィルター
toolbar-quick-filter-bar =
    .title = メッセージを絞り込みます
toolbar-synchronize-label = 同期
toolbar-synchronize =
    .title = カレンダーを更新して変更を同期します
toolbar-delete-event-label = 削除
toolbar-delete-event =
    .title = 選択した予定または ToDo を削除します
toolbar-go-to-today-label = 今日に移動
toolbar-go-to-today =
    .title = 今日の日付へ移動します
toolbar-print-event-label = @@Print@@
toolbar-print-event =
    .title = 予定または ToDo を@@Print@@します
toolbar-new-event-label = 予定
toolbar-new-event =
    .title = @@New-CMD@@予定を作成します
toolbar-new-task-label = ToDo
toolbar-new-task =
    .title = @@New-CMD@@ ToDo を作成します
toolbar-go-back-label = 戻る
toolbar-go-back =
    .title = メッセージ表示履歴を前に戻ります
toolbar-go-forward-label = 進む
toolbar-go-forward =
    .title = メッセージ表示履歴を次に進みます
toolbar-stop-label = 停止
toolbar-stop =
    .title = 送受信処理を中止します
toolbar-throbber-label = アクティブインジケータ
toolbar-throbber =
    .title = アクティブインジケータ
