#filter emptyLines

#define MOZ_LANGPACK_CREATOR The ChatZilla Team

#define MOZ_LANGPACK_HOMEPAGE http://chatzilla.hacksrus.com/

# If non-English locales wish to credit multiple contributors, uncomment this
# variable definition and use the format specified.
#define MOZ_LANGPACK_CONTRIBUTORS <em:contributor>Chiaki Koufugata</em:contributor><em:contributor>Nyozlla</em:contributor><em:contributor>Youhei Tooyama</em:contributor><em:contributor>Tomoya Asai</em:contributor><em:contributor>Atsushi Sakai</em:contributor><em:contributor>Masahiko Imanaka</em:contributor>

#unfilter emptyLines
