# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at http://mozilla.org/MPL/2.0/.

saved-logins =
    .title = 保存されたログイン情報
window-close =
    .key = w
focus-search-shortcut =
    .key = f
focus-search-altshortcut =
    .key = k
copy-site-url-cmd =
    .label = URL をコピー
    .accesskey = y
launch-site-url-cmd =
    .label = URL を開く
    .accesskey = V
copy-username-cmd =
    .label = ユーザー名をコピー
    .accesskey = U
edit-username-cmd =
    .label = ユーザー名を編集
    .accesskey = d
copy-password-cmd =
    .label = パスワードをコピー
    .accesskey = C
edit-password-cmd =
    .label = パスワードを編集
    .accesskey = E
search-filter =
    .accesskey = S
    .placeholder = 検索
column-heading-site =
    .label = サイト
column-heading-username =
    .label = ユーザー名
column-heading-password =
    .label = パスワード
column-heading-time-created =
    .label = 初回使用日
column-heading-time-last-used =
    .label = 最終使用日時
column-heading-time-password-changed =
    .label = 変更日
column-heading-times-used =
    .label = 使用回数
remove =
    .label = 削除
    .accesskey = R
import =
    .label = @@Import@@...
    .accesskey = I
close-button =
    .label = 閉じる
    .accesskey = C
show-passwords =
    .label = パスワードを表示する
    .accesskey = P
hide-passwords =
    .label = パスワードを隠す
    .accesskey = P
logins-description-all = このコンピューターには以下のサイトのログイン情報が保存されています
logins-description-filtered = 次のログイン情報が検索語と一致しました:
remove-all =
    .label = すべて削除
    .accesskey = A
remove-all-shown =
    .label = 対象をすべて削除
    .accesskey = A
remove-all-passwords-prompt = 本当にすべてのパスワードを消去しますか？
remove-all-passwords-title = すべてのパスワードを消去
no-master-password-prompt = パスワードを表示しますか？
auto-fill-logins-and-passwords =
    .label = ログイン情報とパスワードを自動的に入力する
