# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at http://mozilla.org/MPL/2.0/.

select-all-calendars = @@SelectAll@@
select-none-calendars = 選択なし
calendar-creation-wizard-title = @@New-CMD@@カレンダー
calendar-creation-initial-description = カレンダーをこのコンピューターに保存するか、サーバーに保存することができます。サーバーに保存したカレンダーは、リモートからアクセスしたり友人や同僚と共有したりできます。
calendar-creation-initial-computer =
    .label = このコンピューターに保存する
calendar-creation-initial-network =
    .label = ネットワークのサーバーに保存する
calendar-creation-username =
    .value = ユーザー名:
calendar-creation-panel-local-settings =
    .buttonlabelaccept = カレンダーを作成
    .buttonaccesskeyaccept = r
    .buttonlabelextra2 = 戻る
    .buttonaccesskeyextra2 = B
calendar-creation-panel-addon-settings =
    .buttonlabelaccept = カレンダーを作成
    .buttonaccesskeyaccept = r
    .buttonlabelextra2 = 戻る
    .buttonaccesskeyextra2 = B
calendar-creation-panel-network-settings =
    .buttonlabelaccept = カレンダーを検索
    .buttonaccesskeyaccept = F
    .buttonlabelextra2 = 戻る
    .buttonaccesskeyextra2 = B
calendar-creation-panel-select-calendars =
    .buttonlabelaccept = 購読
    .buttonaccesskeyaccept = S
    .buttonlabelextra2 = 戻る
    .buttonaccesskeyextra2 = B
calendar-creation-type =
    .value = カレンダーの形式:
calendar-creation-location =
    .value = 場所:
calendar-creation-location-placeholder =
    .placeholder = カレンダーサーバーの URL またはホスト名
    .default-placeholder = カレンダーサーバーの URL またはホスト名
calendar-creation-network-nocredentials =
    .label = この場所は認証情報を必要としません
calendar-creation-network-loading = カレンダーが見つかるまでしばらくお待ちください。
calendar-creation-network-notfound = この場所にカレンダーが見つかりませんでした。設定を確認してください。
calendar-creation-network-authfail = 入力した認証情報が拒否されました。設定を確認してください。
calendar-creation-network-certerror = この場所にカレンダーが見つかりませんでした。証明書に問題があります。
calendar-creation-network-subscribe-single = 購読するカレンダーを選択してください。
calendar-creation-network-subscribe-multiple = この場所では複数のカレンダー形式が利用できます。カレンダーの形式を選択し、購読するカレンダーにチェックを入れてください。
