# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at http://mozilla.org/MPL/2.0/.

select-all-calendars = @@SelectAll@@
select-none-calendars = 選択なし
calendar-creation-wizard-title = Create New Calendar(^^k
calendar-creation-initial-description = Your calendar can be stored on your computer or be stored on a server in order to access it remotely or share it with your friends or co-workers.(^^k
calendar-creation-initial-computer =
    .label = On My Computer(^^k
calendar-creation-initial-network =
    .label = On the Network(^^k
calendar-creation-username =
    .value = Username:(^^k
calendar-creation-panel-local-settings =
    .buttonlabelaccept = Create Calendar(^^k
    .buttonaccesskeyaccept = r
    .buttonlabelextra2 = Back(^^k
    .buttonaccesskeyextra2 = B
calendar-creation-panel-addon-settings =
    .buttonlabelaccept = Create Calendar(^^k
    .buttonaccesskeyaccept = r
    .buttonlabelextra2 = Back(^^k
    .buttonaccesskeyextra2 = B
calendar-creation-panel-network-settings =
    .buttonlabelaccept = Find Calendars(^^k
    .buttonaccesskeyaccept = F
    .buttonlabelextra2 = Back(^^k
    .buttonaccesskeyextra2 = B
calendar-creation-panel-select-calendars =
    .buttonlabelaccept = Subscribe(^^k
    .buttonaccesskeyaccept = S
    .buttonlabelextra2 = Back(^^k
    .buttonaccesskeyextra2 = B
calendar-creation-type =
    .value = Calendar Type:(^^k
calendar-creation-location =
    .value = Location:(^^k
calendar-creation-location-placeholder =
    .placeholder = URL or host name of the calendar server(^^k
    .default-placeholder = URL or host name of the calendar server(^^k
calendar-creation-network-nocredentials =
    .label = This location doesn’t require credentials(^^k
calendar-creation-network-loading = Please wait while your calendars are being discovered.(^^k
calendar-creation-network-notfound = Could not find calendars at this location. Please check your settings.(^^k
calendar-creation-network-authfail = The credentials you have entered were not accepted. Please check your settings.(^^k
calendar-creation-network-certerror = Could not find calendars at this location because of a certificate problem.(^^k
calendar-creation-network-subscribe-single = Please select the calendars you would like to subscribe to.(^^k
calendar-creation-network-subscribe-multiple = Multiple calendar types are available for this location. Please select the calendar type, then mark the calendars you would like to subscribe to.(^^k
