# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at http://mozilla.org/MPL/2.0/.

header-comment =
    .value = コメント
calendar-item-summary-title = 件名:
calendar-item-summary-calendar = カレンダー:
calendar-item-summary-task-start = 着手日時:
calendar-item-summary-event-start = 開始日時:
calendar-item-summary-task-due = 締切日時:
calendar-item-summary-event-end = 終了日時:
calendar-item-summary-repeat = 繰り返し:
calendar-item-summary-location = 場所:
calendar-item-summary-category = カテゴリー:
calendar-item-summary-organizer = 主催者:
calendar-item-summary-status = 状態:
calendar-item-summary-reminder = アラーム:
calendar-item-summary-attachments = 添付:
calendar-item-summary-status-tentative = 未確定
calendar-item-summary-status-confirmed = 確認済み
calendar-item-summary-event-status-cancelled = キャンセル
calendar-item-summary-todo-status-cancelled = キャンセル
calendar-item-summary-status-needs-action = 行動が必要
calendar-item-summary-status-in-process = 進行中
calendar-item-summary-status-completed = 完了
calendar-item-summary-reminder-none =
    .label = 通知しない
calendar-item-summary-reminder-0-minutes-before =
    .label = 0 分前
calendar-item-summary-reminder-5-minutes-before =
    .label = 5 分前
calendar-item-summary-reminder-15-minutes-before =
    .label = 15 分前
calendar-item-summary-reminder-30-minutes-before =
    .label = 30 分前
calendar-item-summary-reminder-1-hour-before =
    .label = 1 時間前
calendar-item-summary-reminder-2-hours-before =
    .label = 2 時間前
calendar-item-summary-reminder-12-hours-before =
    .label = 12 時間前
calendar-item-summary-reminder-1-day-before =
    .label = 1 日前
calendar-item-summary-reminder-2-days-before =
    .label = 2 日前
calendar-item-summary-reminder-1-week-before =
    .label = 1 週間前
calendar-item-summary-reminder-custom =
    .label = 手動設定...
calendar-item-summary-reminder-multiple =
    .value = 複数のアラーム...
calendar-item-summary-general =
    .value = 一般
calendar-item-summary-attendees =
    .value = 参加者
calendar-item-summary-description =
    .value = 詳細
calendar-item-summary-link =
    .value = 関連リンク
