# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at http://mozilla.org/MPL/2.0/.

dialogAcceptLabelSaveItem = 保存
dialogTitleAddBookmark = @@New-CMD@@ブックマーク
dialogTitleAddMulti = @@New-CMD@@ブックマーク
dialogTitleEdit = "%S" の@@Property@@
dialogTitleAddNewBookmark2 = @@New-CMD@@ブックマークを追加
dialogTitleEditBookmark = “%S” を編集
dialogTitleEditBookmark2 = ブックマークを編集
dialogTitleAddBookmarkFolder = ブックマークフォルダーを追加
dialogTitleEditBookmarkFolder = ブックマークフォルダーを編集
bookmarkAllTabsDefault = [フォルダーの名前]
newFolderDefault = @@NewFolderDefault@@
newBookmarkDefault = @@New-CMD@@ブックマーク
