# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at http://mozilla.org/MPL/2.0/.

spam-settings-title = 迷惑メール
dialog-header-title =
    .value = 迷惑メールフィルターの設定
training-description-spam = フィルターを有効にした場合、どのようなメッセージが迷惑メールなのかを { -brand-short-name } に学習させる必要があります。迷惑メールを受信したら、ヘッダーツールバーの @@[@@迷惑マークを付ける@@]@@ ボタンを押してください。間違って迷惑メールと判断されたメールがあれば、@@[@@非迷惑メール@@]@@ ボタンで訂正してください。迷惑または非迷惑を学習させると、{ -brand-short-name } が自動的に迷惑マークを付けられるようになります。
spam-level-checkbox =
    .label = このアカウントで迷惑メールの学習を有効にする
    .accesskey = E
move-spam-message-menuitem =
    .label = 迷惑メールと判断された受信メッセージを次のフォルダーに移動する:
    .accesskey = M
set-spam-folder-menuitem =
    .label = 次のアカウントの “迷惑メール” フォルダー:
    .accesskey = S
move-message-other =
    .label = その他のフォルダーを指定する:
    .accesskey = O
automatic-spam-purge-checkbox =
    .label = このフォルダーの迷惑メールのうち
    .accesskey = u
automatic-spam-purge-label =
    .value = 日以上前のものは自動的に削除する
trust-addresses-header-label =
    .value = 次のアドレス帳に含まれるメールアドレスを信用する:
    .accesskey = D
allowlist-header-label =
    .value = 送信者が以下に含まれる場合は自動的に迷惑マークを付けない:
    .accesskey = D
isp-headers-checkbox =
    .label = 次の迷惑メールヘッダーを信用する:
    .accesskey = T
isp-warning-description = 有効にした場合、外部で分類された迷惑メールヘッダーを尊重して { -brand-short-name } が自動的に迷惑マークを付けます。
spam-detecting-legend = 迷惑メールの検出
spam-storage-deletion-legend = 格納先と自動削除
spam-classification-legend = 選別
spam-actions-legend = 移動先と保存期間
global-spam-preferences-button =
    .label = 共通の迷惑メール設定...
    .accesskey = G
manage-spam-title = 迷惑メールの管理
manage-spam-header =
    .value = 迷惑メールの管理
training-description-learns = このオプションを有効にすると、迷惑マークを付けたり外したりしたメッセージから { -brand-short-name } が学習します。多くの迷惑メールを学習させることで { -brand-short-name } が正しく検出できるようになります。
spam-auto-detection-checkbox =
    .label = このアカウントの迷惑メールを自動的に検出する
    .accesskey = E
