# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at http://mozilla.org/MPL/2.0/.

offline-dialog-title = オフライン設定
autodetect-connection-label =
    .label = インターネットに接続されたら自動的にモードを切り替える
    .accesskey = d
offline-startup-label = { -brand-short-name } の起動時:
status-radio-last-used =
    .label = 前回の接続モードを使用する
    .accesskey = U
status-radio-ask-connect =
    .label = オンライン接続するか確認する
    .accesskey = k
status-radio-start-online =
    .label = オンラインで開始する
    .accesskey = l
status-radio-start-offline =
    .label = オフラインで開始する
    .accesskey = f
going-online-prompt = 送信トレイの未送信メッセージを送信する
going-online-send =
    .label = 自動的に送信する
    .accesskey = Y
going-online-keep =
    .label = 送信せずに残す
    .accesskey = N
going-online-ask-send =
    .label = 送信する前に確認する
    .accesskey = s
going-offline-prompt = オフラインで読むためにメッセージをダウンロードしますか？
going-offline-download =
    .label = 自動的にダウンロードする
    .accesskey = e
going-offline-keep =
    .label = ダウンロードしない
    .accesskey = o
going-offline-ask-download =
    .label = ダウンロードする前に確認する
    .accesskey = a
autodetect-online-label =
    .label = 検出された状態に自動的に従う
    .accesskey = d
offline-preference-startup-label = 起動時の状態を手動で設定する:
status-radio-remember =
    .label = 前回終了時の状態を記憶する
    .accesskey = R
status-radio-ask =
    .label = オンライン状態を確認する
    .accesskey = k
status-radio-always-online =
    .label = 常にオンライン
    .accesskey = l
status-radio-always-offline =
    .label = 常にオフライン
    .accesskey = f
going-online-label = オンラインになったらすぐに未送信メッセージを送信しますか？
going-online-auto =
    .label = はい
    .accesskey = Y
going-online-not =
    .label = いいえ
    .accesskey = N
going-online-ask =
    .label = 確認する
    .accesskey = s
going-offline-label = オフラインになる前にオフラインで使用するメッセージをダウンロードしますか？
going-offline-auto =
    .label = はい
    .accesskey = e
going-offline-not =
    .label = いいえ
    .accesskey = o
going-offline-ask =
    .label = 確認する
    .accesskey = a
