# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at http://mozilla.org/MPL/2.0/.

migration-wizard =
    .title = 設定移行@@Wizard@@
import-from =
    { PLATFORM() ->
        [windows] オプション、ブックマーク、履歴、パスワードその他のデータを@@Import-suru@@対象を選んでください:
       *[other] 設定、ブックマーク、履歴、パスワードその他のデータを@@Import-suru@@対象を選んでください:
    }
import-from-bookmarks = ブックマークを@@Import-suru@@対象を選んでください:
import-from-ie =
    .label = Microsoft Internet Explorer
    .accesskey = M
import-from-edge =
    .label = Microsoft Edge
    .accesskey = E
import-from-edge-legacy =
    .label = Microsoft Edge Legacy
    .accesskey = L
import-from-edge-beta =
    .label = Microsoft Edge Beta
    .accesskey = d
import-from-nothing =
    .label = 設定を@@Import-sinai@@
    .accesskey = D
import-from-safari =
    .label = Safari
    .accesskey = S
import-from-canary =
    .label = Chrome Canary
    .accesskey = n
import-from-chrome =
    .label = Chrome
    .accesskey = C
import-from-chrome-beta =
    .label = Chrome Beta
    .accesskey = B
import-from-chrome-dev =
    .label = Chrome Dev
    .accesskey = D
import-from-chromium =
    .label = Chromium
    .accesskey = u
import-from-firefox =
    .label = Firefox
    .accesskey = X
import-from-360se =
    .label = 360 Secure Browser
    .accesskey = 3
no-migration-sources = ブックマーク、履歴やパスワードなどの@@Import-suru@@設定やデータを持つ@@Program@@が見つかりませんでした。
import-source =
    .label = 設定とデータの@@-ImportCMD@@
import-items-title =
    .label = @@Import-suru@@項目
import-items-description = @@Import-suru@@項目を選択してください:
import-migrating-title =
    .label = @@Import-site@@います...
import-migrating-description = 次の項目を現在@@Import-site@@います...
import-select-profile-title =
    .label = プロファイルの選択
import-select-profile-description = @@Import-suru@@プロファイルを選択してください:
import-done-title =
    .label = @@ImportNoun@@完了
import-done-description = 次のデータが正常に@@Import-sare@@ました:
import-close-source-browser = 続ける前に、選択したブラウザーが閉じられていることを確認してください。
# Displays which browser the bookmarks are being imported from
#
# Variables:
#   $source (String): The browser the user has chosen to import bookmarks from.
imported-bookmarks-source = { $source } から
source-name-ie = Internet Explorer
source-name-edge = Microsoft Edge
source-name-edge-beta = Microsoft Edge Beta
source-name-safari = Safari
source-name-canary = Google Chrome Canary
source-name-chrome = Google Chrome
source-name-chrome-beta = Google Chrome Beta
source-name-chrome-dev = Google Chrome Dev
source-name-chromium = Chromium
source-name-firefox = Mozilla Firefox
source-name-360se = 360 Secure Browser
imported-safari-reading-list = リーディングリスト (Safari から)
imported-edge-reading-list = リーディングリスト (Edge から)

# Import Sources
# Note: When adding an import source for profile reset, add the string name to
# resetProfile.js if it should be listed in the reset dialog.

browser-data-ie-1 =
    .label = インターネットオプション
    .value = インターネットオプション
browser-data-edge-1 =
    .label = 設定
    .value = 設定
browser-data-safari-1 =
    .label = 設定
    .value = 設定
browser-data-chrome-1 =
    .label = 設定
    .value = 設定
browser-data-canary-1 =
    .label = 設定
    .value = 設定
browser-data-360se-1 =
    .label = 設定
    .value = 設定
browser-data-ie-2 =
    .label = Cookie
    .value = Cookie
browser-data-edge-2 =
    .label = Cookie
    .value = Cookie
browser-data-safari-2 =
    .label = Cookie
    .value = Cookie
browser-data-chrome-2 =
    .label = Cookie
    .value = Cookie
browser-data-canary-2 =
    .label = Cookie
    .value = Cookie
browser-data-firefox-2 =
    .label = Cookie
    .value = Cookie
browser-data-360se-2 =
    .label = Cookie
    .value = Cookie
browser-data-ie-4 =
    .label = 表示履歴
    .value = 表示履歴
browser-data-edge-4 =
    .label = 表示履歴
    .value = 表示履歴
browser-data-safari-4 =
    .label = 表示履歴
    .value = 表示履歴
browser-data-chrome-4 =
    .label = 表示履歴
    .value = 表示履歴
browser-data-canary-4 =
    .label = 表示履歴
    .value = 表示履歴
browser-data-firefox-history-and-bookmarks-4 =
    .label = 履歴とブックマーク
    .value = 履歴とブックマーク
browser-data-360se-4 =
    .label = 表示履歴
    .value = 表示履歴
browser-data-ie-8 =
    .label = 入力フォームの履歴
    .value = 入力フォームの履歴
browser-data-edge-8 =
    .label = 入力フォームの履歴
    .value = 入力フォームの履歴
browser-data-safari-8 =
    .label = 入力フォームの履歴
    .value = 入力フォームの履歴
browser-data-chrome-8 =
    .label = 入力フォームの履歴
    .value = 入力フォームの履歴
browser-data-canary-8 =
    .label = 入力フォームの履歴
    .value = 入力フォームの履歴
browser-data-firefox-8 =
    .label = 入力フォームの履歴
    .value = 入力フォームの履歴
browser-data-360se-8 =
    .label = 入力フォームの履歴
    .value = 入力フォームの履歴
browser-data-ie-16 =
    .label = 保存されているパスワード
    .value = 保存されているパスワード
browser-data-edge-16 =
    .label = 保存されているパスワード
    .value = 保存されているパスワード
browser-data-safari-16 =
    .label = 保存されているパスワード
    .value = 保存されているパスワード
browser-data-chrome-16 =
    .label = 保存されているパスワード
    .value = 保存されているパスワード
browser-data-canary-16 =
    .label = 保存されているパスワード
    .value = 保存されているパスワード
browser-data-firefox-16 =
    .label = 保存されているパスワード
    .value = 保存されているパスワード
browser-data-360se-16 =
    .label = 保存されているパスワード
    .value = 保存されているパスワード
browser-data-ie-32 =
    .label = お気に入り
    .value = お気に入り
browser-data-edge-32 =
    .label = お気に入り
    .value = お気に入り
browser-data-safari-32 =
    .label = ブックマーク
    .value = ブックマーク
browser-data-chrome-32 =
    .label = ブックマーク
    .value = ブックマーク
browser-data-canary-32 =
    .label = ブックマーク
    .value = ブックマーク
browser-data-360se-32 =
    .label = ブックマーク
    .value = ブックマーク
browser-data-ie-64 =
    .label = その他のデータ
    .value = その他のデータ
browser-data-edge-64 =
    .label = その他のデータ
    .value = その他のデータ
browser-data-safari-64 =
    .label = その他のデータ
    .value = その他のデータ
browser-data-chrome-64 =
    .label = その他のデータ
    .value = その他のデータ
browser-data-canary-64 =
    .label = その他のデータ
    .value = その他のデータ
browser-data-firefox-other-64 =
    .label = その他のデータ
    .value = その他のデータ
browser-data-360se-64 =
    .label = その他のデータ
    .value = その他のデータ
browser-data-firefox-128 =
    .label = @@Window@@とタブ
    .value = @@Window@@とタブ
