# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at http://mozilla.org/MPL/2.0/.

report-broken-site-mainview-title = 動作しないサイトを報告
report-broken-site-panel-header =
    .label = 動作しないサイトを報告
    .title = 動作しないサイトを報告
report-broken-site-panel-intro-text = ご報告は、{ -brand-product-name } の問題を理解して解決し、すべての人にとって製品をより良くするために役立ちます。
report-broken-site-panel-learn-more-link = 詳細情報
report-broken-site-panel-intro = { -brand-product-name } の改善にご協力ください。{ -vendor-short-name } はあなたが送信した情報をウェブサイトの問題を解決するために使用します。
report-broken-site-panel-url = URL
report-broken-site-panel-reason-label = 何が動作しませんか？
report-broken-site-panel-reason-optional-label = 不具合の詳細 (任意)
report-broken-site-panel-reason-choose =
    .label = 不具合の状態を選んでください
report-broken-site-panel-reason-load =
    .label = サイトが読み込まれない
# These terms are referring to ecommerce websites
report-broken-site-panel-reason-checkout =
    .label = 支払いまたはチェックアウト、買い物ができない
report-broken-site-panel-reason-slow2 =
    .label = サイトの動作が遅い
report-broken-site-panel-reason-media2 =
    .label = 動画が再生されない、または読み込まれない
report-broken-site-panel-reason-content2 =
    .label = コンテンツの一部が表示されない
report-broken-site-panel-reason-account2 =
    .label = ログインまたは登録ができない
report-broken-site-panel-reason-adblocker2 =
    .label = 広告ブロッカーの無効化を求められる
report-broken-site-panel-reason-notsupported =
    .label = ブラウザーがサポートされていない、またはブロックされている
report-broken-site-panel-reason-other =
    .label = その他
report-broken-site-panel-description-label = 問題の詳細
report-broken-site-panel-description =
    .placeholder = 何が起こったのか、本来は何が起こるべきだったのかをご記入ください。トラッキング防止機能を無効にしていたかも教えてください。
report-broken-site-panel-description-optional-label = 問題を具体的に記入してください (任意)
report-broken-site-panel-send-more-info-link = 詳しい情報を送信
report-broken-site-panel-button-cancel =
    .label = キャンセル
report-broken-site-panel-button-okay =
    .label = OK
report-broken-site-panel-button-send =
    .label = 送信
report-broken-site-panel-report-sent-label = レポートが送信されました
report-broken-site-panel-report-sent-header =
    .label = レポートが送信されました
    .title = レポートが送信されました
report-broken-site-panel-report-sent-text = ウェブをすべての人々のためにオープンでアクセシブルにし、良いものにする { -brand-product-name } へのご協力に感謝します。
report-broken-site-panel-invalid-url-label = 正しい URL を入力してください
report-broken-site-panel-missing-reason-label = 不具合の対象を選んでください
report-broken-site-panel-blocked-trackers-label =
    .label = トラッキング防止機能がブロックした URL を送信する
report-broken-site-panel-blocked-trackers-description = 強化型トラッキング防止機能により、ウェブサイトが正しく動作するために必要なトラッカーやスクリプトがブロックされている可能性があります。
report-broken-site-panel-preview-button =
    .label = レポートをプレビュー
report-broken-site-panel-preview-header =
    .label = レポートのプレビュー
