# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at http://mozilla.org/MPL/2.0/.


## Variables:
##   $host (String): A website host address

network-connection-status-looking-up = { $host } のアドレス解決をしています...
network-connection-status-connected = { $host } に接続しました...
network-connection-status-sending-request = { $host } に要求を送信しています...
network-connection-status-transferring-data = { $host } からデータを転送しています...
network-connection-status-connecting = { $host } に接続しています...
network-connection-status-read = { $host } を読み込みました
network-connection-status-wrote = { $host } を書き込みました
network-connection-status-waiting = { $host } の応答を待っています...
network-connection-status-looked-up = { $host } を調べています...
network-connection-status-tls-handshake = { $host } との TLS ハンドシェイクを実行しています...
network-connection-status-tls-handshake-finished = { $host } の TLS ハンドシェイクが完了しました...
