# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at http://mozilla.org/MPL/2.0/.

# Download Cert dialog
# LOCALIZATION NOTE(newCAMessage1):
# %S is a string representative of the certificate being downloaded/imported.
newCAMessage1 = “%S” が行う認証のうち、信頼するものを選択してください。
unnamedCA = 名前のない認証局
# PKCS#12 file dialogs
getPKCS12FilePasswordMessage = この証明書のバックアップの暗号化に用いたパスワードを入力してください:
# Page Info
pageInfo_NoEncryption = 接続が暗号化されていません
pageInfo_Privacy_None1 = ウェブサイト %S は表示中のページの暗号化をサポートしていません。
pageInfo_Privacy_None2 = 暗号化せずにインターネットに送信された情報は他人に傍受される可能性があります。
pageInfo_Privacy_None4 = 表示中のページは転送される前から暗号化されていません。
# LOCALIZATION NOTE (pageInfo_EncryptionWithBitsAndProtocol and pageInfo_BrokenEncryption):
# %1$S is the name of the encryption standard,
# %2$S is the key size of the cipher.
# %3$S is protocol version like "SSL 3" or "TLS 1.2"
pageInfo_EncryptionWithBitsAndProtocol = 接続が暗号化されています (%1$S、鍵長 %2$S bit、%3$S)
pageInfo_BrokenEncryption = 脆弱な暗号化 (%1$S、鍵長 %2$S bit、%3$S)
pageInfo_Privacy_Encrypted1 = 表示中のページはインターネット上に送信される前に暗号化されています。
pageInfo_Privacy_Encrypted2 = 暗号化によってコンピューター間の通信の傍受は困難になり、このページをネットワークで転送中に誰かにその内容をのぞき見られる可能性は低くなります。
pageInfo_MixedContent = 一部の接続だけが暗号化されています
pageInfo_MixedContent2 = 表示しているページの一部はインターネットに転送される前に暗号化されていません。
pageInfo_WeakCipher = このウェブサイトへの接続に使用されている暗号は強度が弱くプライベートではありません。他者があなたの情報を見たりウェブサイトの動作を変更できます。
pageInfo_CertificateTransparency_Compliant = このウェブサイトは証明書の透明性ポリシーに準拠しています。
# Token Manager
password_not_set = (設定なし)
